import {
  User,
  Vendor,
  Course,
  Enrollment,
  Role,
  Status,
  CourseList,
} from "./types";

// A single source of truth for all authenticatable entities.
export const allUsers: (User | Vendor)[] = [
  // User
  {
    id: "u1",
    name: "Raj Kumar",
    email: "user@example.com",
    password: "password",
    role: Role.USER,
    rank: "Deck Cadet",
    profilePictureUrl:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=3387&auto=format&fit=crop",
    phone: "987654321090",
  },
  // Admin
  {
    id: "a1",
    name: "Alex Johnson",
    email: "admin@example.com",
    password: "password",
    role: Role.ADMIN,
    profilePictureUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=3540&auto=format&fit=crop",
    phone: "+1 234 567 890",
  },
  // Vendors
  {
    id: "v1",
    name: "BlueWave Maritime Academy",
    email: "vendor@example.com",
    password: "password",
    role: Role.VENDOR,
    instituteName: "BlueWave Maritime",
    accreditationNo: "DG-S-ACCRED-1138",
    address: "123 Ocean Drive, Mumbai, India",
    contactPerson: "Capt. Sharma",
    documents: [
      {
        name: "accreditation.pdf",
        url: "#",
        size: "1.2MB",
        uploadedDate: "12 Jan 2024",
      },
    ],
    status: Status.APPROVED,
    submissionDate: "2023-10-15",
  },
  {
    id: "v2",
    name: "Seafarer's Choice Institute",
    email: "vendor2@example.com",
    password: "password",
    role: Role.VENDOR,
    instituteName: "Seafarer's Choice",
    accreditationNo: "DG-S-ACCRED-1150",
    address: "456 Marine Parade, Chennai, India",
    contactPerson: "Ms. Priya Singh",
    documents: [
      {
        name: "Incorporation Certificate.pdf",
        url: "#",
        size: "1.2MB",
        uploadedDate: "26 Oct 2023",
      },
      {
        name: "DG Shipping License.pdf",
        url: "#",
        size: "850KB",
        uploadedDate: "26 Oct 2023",
      },
    ],
    status: Status.PENDING,
    submissionDate: "2023-10-26",
  },
  {
    id: "v3",
    name: "Poseidon Training Center",
    email: "vendor3@example.com",
    password: "password",
    role: Role.VENDOR,
    instituteName: "Poseidon Training",
    accreditationNo: "DG-S-ACCRED-1192",
    address: "789 Port Road, Kolkata, India",
    contactPerson: "Mr. Anik Das",
    documents: [
      {
        name: "Audit Report.pdf",
        url: "#",
        size: "2.5MB",
        uploadedDate: "15 Nov 2023",
      },
    ],
    status: Status.PENDING,
    submissionDate: "2023-10-25",
  },
  {
    id: "v4",
    name: "Nautical Skills Inc.",
    email: "vendor4@example.com",
    password: "password",
    role: Role.VENDOR,
    instituteName: "Nautical Skills Inc.",
    accreditationNo: "DG-S-ACCRED-1205",
    address: "101 Coastline Ave, Goa, India",
    contactPerson: "Mr. Fernandes",
    documents: [],
    status: Status.PENDING,
    submissionDate: "2023-10-24",
  },
];

// Derived arrays for components that need specific roles.
export const users: User[] = allUsers.filter(
  (u) => u.role === Role.USER || u.role === Role.ADMIN
);
export const vendors: Vendor[] = allUsers.filter(
  (u) => u.role === Role.VENDOR
) as Vendor[];

export const courses: Course[] = [
  {
    id: "c1",
    courseCode: "STCW-001",
    title: "STCW Basic Safety Training",
    instituteId: "v1",
    instituteName: "BlueWave Maritime",
    duration: "5 days",
    fee: 4500,
    location: "Mumbai, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 20,
    startDate: "2024-08-01",
    description: "Comprehensive basic safety training as per STCW convention.",
    imageUrl: "/assets/STCWBasicSafetyTraining.jpeg",
    isDGApproved: true,
  },
  {
    id: "c2",
    courseCode: "AD-C-002",
    title: "Advanced Fire Fighting",
    instituteId: "v2",
    instituteName: "Seafarer's Choice",
    duration: "3 days",
    fee: 8000,
    location: "Chennai, India",
    type: "Offline",
    status: Status.PENDING,
    seats: 15,
    startDate: "2024-08-10",
    description: "Advanced techniques for fire fighting on board ships.",
    imageUrl: "/assets/AdvancedFireFighting.jpg",
    isDGApproved: true,
  },
  {
    id: "c3",
    courseCode: "MED-A-003",
    title: "Medical First Aid",
    instituteId: "v3",
    instituteName: "Poseidon Training",
    duration: "4 days",
    fee: 6200,
    location: "Kolkata, India",
    type: "Offline",
    status: Status.REJECTED,
    seats: 30,
    startDate: "2024-09-01",
    description: "Essential medical first aid skills for seafarers.",
    imageUrl: "/assets/MedicalFirstAid.jpg",
    isDGApproved: true,
  },
  {
    id: "c4",
    courseCode: "PSC-001",
    title: "Proficiency in Survival Craft",
    instituteId: "v4",
    instituteName: "Nautical Skills Inc.",
    duration: "4 days",
    fee: 6200,
    location: "Goa, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 20,
    startDate: "2024-08-15",
    description: "Training for survival craft and rescue boats operations.",
    imageUrl: "/assets/ProficiencyInSurvivalCraft.jpg",
    isDGApproved: true,
  },
  {
    id: "c5",
    courseCode: "RADAR-01",
    title: "Radar & ARPA Simulation",
    instituteId: "v1",
    instituteName: "BlueWave Maritime Academy",
    duration: "10 days",
    fee: 9500,
    location: "Online",
    type: "Online",
    status: Status.APPROVED,
    seats: 12,
    startDate: "2024-09-05",
    description: "Simulator-based training for radar observation.",
    imageUrl: "/assets/Radar&ARPASimulation.jpg",
    isDGApproved: true,
  },
  {
    id: "c6",
    courseCode: "PSSR-C",
    title: "PST & PSSR Combined",
    instituteId: "v2",
    instituteName: "Seafarer's Choice Institute",
    duration: "5 days",
    fee: 5000,
    location: "Worldwide",
    type: "Online",
    status: Status.APPROVED,
    seats: 25,
    startDate: "2024-07-20",
    description:
      "Personal Survival Techniques & Personal Safety and Social Responsibilities.",
    imageUrl: "/assets/PST&PSSRCombined.jpg",
    isDGApproved: true,
  },
  {
    id: "c7",
    courseCode: "MAR-004",
    title: "Ship Security Officer",
    instituteId: "v4",
    instituteName: "Seven Seas Academy",
    duration: "4 days",
    fee: 6200,
    location: "Chennai, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 20,
    startDate: "2024-09-15",
    description:
      "Understand and implement the ship security plan under the ISPS code.",
    imageUrl: "assets/ShipSecurityOfficer.jpg",
    isDGApproved: true,
  },
  {
    id: "c8",
    courseCode: "GMDSS-01",
    title: "GMDSS General Operator's",
    instituteId: "v1",
    instituteName: "BlueWave Maritime",
    duration: "12 days",
    fee: 15000,
    location: "Mumbai, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 10,
    startDate: "2024-10-01",
    description: "Global Maritime Distress and Safety System training.",
    imageUrl: "/assets/GMDSSGeneralOperator.jpg",
    isDGApproved: true,
  },
  {
    id: "c9",
    courseCode: "ECDIS-01",
    title: "ECDIS Type-Specific",
    instituteId: "v1",
    instituteName: "BlueWave Maritime",
    duration: "2 days",
    fee: 8500,
    location: "Online",
    type: "Online",
    status: Status.APPROVED,
    seats: 50,
    startDate: "2024-08-25",
    description: "Electronic Chart Display and Information System training.",
    imageUrl: "/assets/ECDISType-Specific.jpg",
    isDGApproved: true,
  },
  {
    id: "c10",
    courseCode: "BTM-01",
    title: "Bridge Team Management",
    instituteId: "v3",
    instituteName: "Poseidon Training",
    duration: "5 days",
    fee: 12000,
    location: "Kolkata, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 15,
    startDate: "2024-09-10",
    description: "Enhance bridge resource management skills.",
    imageUrl: "/assets/BridgeTeamManagement.jpg",
    isDGApproved: true,
  },
  {
    id: "c11",
    courseCode: "ERM-01",
    title: "Engine Room Resource Mgt",
    instituteId: "v2",
    instituteName: "Seafarer's Choice",
    duration: "5 days",
    fee: 11000,
    location: "Chennai, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 15,
    startDate: "2024-09-20",
    description: "Resource management for engine room personnel.",
    imageUrl: "/assets/EngineRoomResourceMgt.jpg",
    isDGApproved: true,
  },
  {
    id: "c12",
    courseCode: "CHEM-01",
    title: "Chemical Tanker Familiarization",
    instituteId: "v4",
    instituteName: "Nautical Skills Inc.",
    duration: "6 days",
    fee: 9000,
    location: "Goa, India",
    type: "Offline",
    status: Status.APPROVED,
    seats: 20,
    startDate: "2024-10-05",
    description: "Basic training for chemical tanker operations.",
    imageUrl: "/assets/ChemicalTankerFamiliarization.jpg",
    isDGApproved: true,
  },
];

export const enrollments: Enrollment[] = [
  { id: "e1", userId: "u1", courseId: "c1", enrollmentDate: "2024-07-10" },
  { id: "e2", userId: "u1", courseId: "c2", enrollmentDate: "2024-07-11" },
  { id: "e3", userId: "u1", courseId: "c3", enrollmentDate: "2024-07-12" },
  { id: "e4", userId: "u1", courseId: "c4", enrollmentDate: "2024-07-13" },
  { id: "e5", userId: "u1", courseId: "c5", enrollmentDate: "2024-07-14" },
];

export const courselist: CourseList[] = [
  {
    id: 1,
    courseName: "BST-001 Basic STCW Safety Training",
    category: "Basic",
    targetAudience: "All Seafarers",
    entryRequirements:
      "Proof of Indian Citizenship + INDoS Number + Medical Fitness Certificate",
    duration: "12 days",
    validity: "5 years",
    courseOverview:
      "IMO Model Courses 1.19, 1.20, 1.21 & 1.13; DGS Trg Circular 06/2018",
    addtionalNotes: "Bring safety shoes for drills",
  },
  {
    id: 2,
    courseName:
      "BTLGTCO-002 (Basic Training Liquified Gas Tanker Cargo Operations)",
    category: "Basic",
    targetAudience: "Officers & personnel handling Liquified Gas Tanker cargo",
    entryRequirements:
      "Valid Basic Safety STCW (PST/PSSR/EFA/FPFF) OR FPFF Aug OR FPFF + PTFF + Proof of Citizenship + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.04 and STCW Reg V/1-2",
    addtionalNotes: "—",
  },
  {
    id: 3,
    courseName: "BTOCTCO-003 (Basic Training Oil & Chemical Tanker Cargo Ops)",
    category: "Basic",
    targetAudience: "Officers handling Oil/Chemical tanker cargo",
    entryRequirements:
      "Valid Basic STCW (PST/PSSR/EFA/FPFF) OR FPFF Aug OR FPFF + PTFF + Proof of Citizenship + INDoS",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.01 & STCW Reg V/1-1",
    addtionalNotes: "—",
  },
  {
    id: 4,
    courseName: "EFA-004 (Elementary First Aid)",
    category: "Basic",
    targetAudience: "All Seafarers with old EFA certificate",
    entryRequirements:
      "Old EFA Certificate + Indian CDC + INDoS + Proof of Citizenship",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.13",
    addtionalNotes: "—",
  },
  {
    id: 5,
    courseName: "PSF-005 (Passenger Ship Familiarization / Crowd Management)",
    category: "Basic",
    targetAudience: "Personnel employed on passenger ships",
    entryRequirements: "Proof of Citizenship + INDoS",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.28 & DGS Circular 10/2004",
    addtionalNotes: "—",
  },
  {
    id: 6,
    courseName: "PSSR-006 (Personal Safety & Social Responsibility)",
    category: "Basic",
    targetAudience: "Seafarers with old PSSR certificate",
    entryRequirements: "Old PSSR + Indian CDC + INDoS + Proof of Citizenship",
    duration: "4 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.21",
    addtionalNotes: "—",
  },
  {
    id: 7,
    courseName: "STSDSD-007 STSDSD",
    category: "Basic",
    targetAudience: "Seafarers designated for Security Duties",
    entryRequirements: "Citizenship Proof + INDoS Number",
    duration: "2 days",
    validity: "Unlimited",
    courseOverview: "STCW 2010 Sec A-VI/6 & DGS Circular 27/2012",
    addtionalNotes: "—",
  },
  {
    id: 8,
    courseName: "AFF-008 Advanced Fire Fighting",
    category: "Advanced",
    targetAudience: "Seafarers required to control firefighting operations",
    entryRequirements:
      "FPFF certificate + Proof of Citizenship + INDoS + Medical Fitness + 1 year sea service (6 months for cadets)",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview:
      "IMO Model Course 2.03 & Annex 2 of IMO Resolution A437(XII)",
    addtionalNotes:
      "Bring safety shoes for drills. AFF Refresher every 5 years",
  },
  {
    id: 9,
    courseName:
      "ATCTCO-009 (Advanced Training Chemical Tanker Cargo Operations)",
    category: "Advanced",
    targetAudience: "Officers responsible for handling chemical tanker cargo",
    entryRequirements:
      "Valid OTF/BTOCTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Proof of Citizenship + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.02 & STCW Reg V/1-1",
    addtionalNotes: "—",
  },
  {
    id: 10,
    courseName:
      "ATLGTCO-010 (Advanced Training Liquified Gas Tanker Cargo Operations)",
    category: "Advanced",
    targetAudience:
      "Masters, Chief Eng., Chief Mates, 2nd Engineers & cargo officers",
    entryRequirements:
      "Valid GTF/BTLGTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.05 & STCW Reg V/1-2",
    addtionalNotes: "—",
  },
  {
    id: 11,
    courseName: "ATOTCO-011 (Advanced Training Oil Tanker Cargo Operations)",
    category: "Advanced",
    targetAudience: "Officers handling Oil Tanker cargo",
    entryRequirements:
      "Valid OTF/BTOCTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.02 & STCW Reg V/1",
    addtionalNotes: "—",
  },
  {
    id: 12,
    courseName: "CSO–012 Company Security Officer",
    category: "Advanced",
    targetAudience:
      "Officers employed or likely to be Company Security Officers",
    entryRequirements:
      "Company letter / COC / CDC + Citizenship Proof + INDoS (for seafarers)",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.20 & DGS Circular 3/2005",
    addtionalNotes: "—",
  },
  {
    id: 13,
    courseName: "MC–-13 Master Medical Care",
    category: "Advanced",
    targetAudience:
      "Masters, Chief Mates & Second Mates responsible for medical care onboard",
    entryRequirements: "MFA + COC Second Mate + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited (tentative)",
    courseOverview: "IMO Model 1.15 & DGS Circular 9/2004",
    addtionalNotes: "—",
  },
  {
    id: 14,
    courseName: "MFA–014 Medical First Aid",
    category: "Advanced",
    targetAudience: "All Seafarers",
    entryRequirements:
      "Valid EFA + 6 months onboard service + Citizenship Proof + INDoS",
    duration: "4 days",
    validity: "Unlimited (tentative)",
    courseOverview: "IMO Model 1.14 & STCW Circular 8/2004",
    addtionalNotes: "—",
  },
  {
    id: 15,
    courseName: "MR-0015 MR & UT – Master’s Refresher & Updating",
    category: "Advanced",
    targetAudience: "Certificate of Service (Master FG) holders",
    entryRequirements: "CoS Master FG + INDoS",
    duration: "11 days",
    validity: "5 years",
    courseOverview: "STCW 2010 Training Circular 12/2012",
    addtionalNotes: "Requires PSCRB & AFF modules; ECDIS separate",
  },
  {
    id: 16,
    courseName: "PFSOC-0016 Port Facility Security Officer",
    category: "Advanced",
    targetAudience: "Personnel employed as PFSO",
    entryRequirements:
      "Company letter / COC / CDC + Citizenship Proof + INDoS (for seafarers)",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.21 & DGS Circular 7/2005",
    addtionalNotes: "—",
  },
  {
    id: 17,
    courseName: "PSCRB-017 Proficiency in Survival Craft & Rescue Boat",
    category: "Advanced",
    targetAudience:
      "Seafarers operating life-saving appliances or taking charge of rescue crafts",
    entryRequirements:
      "4 Basic STCW modules + CDC + 1 year sea service (6 months cadets) + Citizenship Proof + INDoS + Medical Fitness",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.23 & DGS Circular 12/2005",
    addtionalNotes:
      "Bring safety shoes, swimming costume & towel; PSCRB Refresher every 5 years",
  },
  {
    id: 18,
    courseName: "SBSOC–018 Shipboard Safety Officer Course (Value Added)",
    category: "Advanced",
    targetAudience: "Nautical Officers, Engineers, ETOs, Superintendents",
    entryRequirements:
      "Valid CoC/CoS or sponsorship + 12 months sea service + Passport & CDC",
    duration: "2 days",
    validity: "Unlimited",
    courseOverview: "STCW Code Tables A-II/2, A-III/2 & IMO Model 3.11",
    addtionalNotes: "—",
  },
  {
    id: 19,
    courseName: "SSO–019 Ship Security Officer",
    category: "Advanced",
    targetAudience: "Seafarers designated as SSO",
    entryRequirements:
      "Company letter / COC / CDC + 12 months sea service + Citizenship Proof + INDoS",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.19 & DGS Circular 34/2004",
    addtionalNotes: "—",
  },
  {
    id: 20,
    courseName: "VICT–020 Vertical Integration Course for Trainers",
    category: "Advanced",
    targetAudience:
      "Personnel desiring to be certified as Trainers & Assessors",
    entryRequirements: "INDoS + relevant qualifications per DGS Order 05/2016",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 6.09 & STCW Section V-IV/2",
    addtionalNotes: "Formal dress code (suit & tie) for evaluation",
  },
  {
    id: 21,
    courseName: "ARPA–021 Automatic Radar Plotting Aid",
    category: "Simulator",
    targetAudience: "NWKOs",
    entryRequirements:
      "ROSC + 12 months sea service + CDC + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.07; DG Shipping Circular 6/2004",
    addtionalNotes: "—",
  },
  {
    id: 22,
    courseName: "ECDIS–022 Electronic Chart Display & Information System",
    category: "Simulator",
    targetAudience: "Navigational watch officers using ECDIS",
    entryRequirements:
      "Deck cadets with 6 months sea service OR deck ratings completing competency + ROSC + ARPA + 3 months bridge watch + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "DG Shipping Circular 29/2012",
    addtionalNotes: "—",
  },
  {
    id: 23,
    courseName: "GMDSS–023 Global Maritime Distress & Safety System",
    category: "Simulator",
    targetAudience:
      "Seafarers responsible for radio communication / COC applicants",
    entryRequirements: "10+2 PCM or COC/NWKO + Citizenship Proof + INDoS",
    duration: "12 days",
    validity: "10 years",
    courseOverview: "IMO Model 1.25 & STCW Section V-IV/2",
    addtionalNotes: "—",
  },
  {
    id: 24,
    courseName: "RANSCO–024 Radar ARPA Navigation & Simulator Course",
    category: "Simulator",
    targetAudience: "2nd Mate COC holders",
    entryRequirements: "ROSC + ARPA + 2nd Mate COC + Citizenship Proof + INDoS",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.08 & STCW Circular 7/2004",
    addtionalNotes: "—",
  },
  {
    id: 25,
    courseName: "ROSC–025 Radar Observers Simulator Course",
    category: "Simulator",
    targetAudience: "Seafarers desiring NWKO certification",
    entryRequirements:
      "12 months sea service + CDC + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.07; DG Shipping Circular 5/2004",
    addtionalNotes: "—",
  },
  {
    id: 26,
    courseName: "SMS–026 Ship Manoeuvring Simulator",
    category: "Simulator",
    targetAudience: "Deck officers at management level",
    entryRequirements:
      "COC Chief Mate FG / Mate HT + 18 months sea service + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "DG Shipping Circular 6/2005",
    addtionalNotes: "—",
  },
  {
    id: 27,
    courseName: "FPFFR–027 Fire Prevention & Fire Fighting Refresher",
    category: "Refresher",
    targetAudience: "Seafarers with FPFF valid 5 years earlier",
    entryRequirements: "Valid FPFF / FPFF R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 6/2011 & STCW Table A-VI/1-2",
    addtionalNotes: "Bring safety shoes",
  },
  {
    id: 28,
    courseName: "MCRUT–028 Medical Care Refresher & Updating Training",
    category: "Refresher",
    targetAudience: "Officers holding MC/MC RUT valid 5 years earlier",
    entryRequirements: "Valid MC / MC RUT + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 17/2013 & MLC 2006",
    addtionalNotes: "—",
  },
  {
    id: 29,
    courseName: "MFARUT–029 Medical First Aid Refresher",
    category: "Refresher",
    targetAudience: "MFA/MFA RUT holders 5 years old",
    entryRequirements: "Valid MFA / MFA RUT + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 17/2013 & MLC 2006",
    addtionalNotes: "—",
  },
  {
    id: 30,
    courseName: "PSTR–030 Personal Survival Techniques Refresher",
    category: "Refresher",
    targetAudience: "PST / PST R holders 5 years old",
    entryRequirements: "Valid PST / PST R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 6/2011 & STCW Table A-VI/1-1",
    addtionalNotes: "Bring swimwear & towel",
  },
  {
    id: 31,
    courseName: "AFFR–031 Advance Fire Fighting Refresher",
    category: "Refresher",
    targetAudience: "Officers holding AFF / AFF R older than 5 years",
    entryRequirements:
      "Valid AFF / AFF R / AFFFPFF R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping ENGG Circular 2/2015",
    addtionalNotes: "Bring safety shoes",
  },
  {
    id: 32,
    courseName: "PSCRBR–032 Proficiency in Survival Craft Refresher",
    category: "Refresher",
    targetAudience: "PSCRB holders",
    entryRequirements: "Valid PSCRB + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DGS training requirement",
    addtionalNotes: "—",
  },
];
